import { Loading, GlobalModals } from "@/components/Shared";
import "./globals.css";
import { AppContexts } from "@/contexts";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Mesh Forum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>
          <AppContexts>
            <Toaster position="top-center" />
            <GlobalModals />
            {children}
          </AppContexts>
        </Suspense>
      </body>
    </html>
  );
}
