import { AppContexts } from "@/contexts";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Mesh Forum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContexts>
          <Toaster toastOptions={{ duration: 2000 }} />
          {children}
        </AppContexts>
      </body>
    </html>
  );
}
